#!/bin/sh

# Experimental new build system.

SRCDIR=`pwd`
OBJDIR=`pwd`/.obj
DESTDIR=`pwd`
GENMAKEDIR=`pwd`/gm

LIBDIR="$OBJDIR"

# Host compiler setup.

HOSTCC="g++ -g -Wall"
HOSTCPP="cpp"

# ACK setup.

ACKDIR=/home/dg/projects/ack/rt
Z80CC="ACKDIR=$ACKDIR $ACKDIR/bin/acc -mz80 -ansi"

INCLUDES=""
DEFINES=""
STACK="S"

OBJS=
CLEANABLE=
BUILDABLE=

# Functions.

. $GENMAKEDIR/host.sh

install() {
	local source="$1"
	local dest="$2"

	BUILDABLE="$BUILDABLE $dest"
	CLEANABLE="$CLEANABLE $dest"
cat <<EOF
$dest: $source
	@echo -e "INSTALL\t$dest"
	@mkdir -p \$(dir \$@)
	@cp \$^ \$@
EOF
}

makefileheader() {
	echo "include $GENMAKEDIR/lib.mk"
}

makefilefooter() {
	echo "all: $BUILDABLE"
	echo "clean:"
	echo -e "\t@echo CLEAN"
	echo -e "\t@rm -f $CLEANABLE"
}

push() {
	eval "STACK_S$STACK=\"$STACK\""
	eval "STACK=\"S$STACK\""
	eval "INCLUDES_$STACK=\"$INCLUDES\""
	eval "DEFINES_$STACK=\"$DEFINES\""

	OBJS=
	SRCS=
}

pop() {
	eval "INCLUDES=\"\${INCLUDES_${STACK}}\""
	eval "DEFINES=\"\${DEFINES_${STACK}}\""
	eval "STACK=\"\${STACK_${STACK}}\""
}

addinclude() {
	INCLUDES="$INCLUDES -I$1"
}

adddefine() {
	DEFINES="$DEFINES $1"
}

addbuildable() {
	BUILDABLE="$BUILDABLE $@"
}

addcleanable() {
	CLEANABLE="$CLEANABLE $@"
}

include() {
	. "$1"
}

# ===========================================================================
#                                BUILD RULES
# ===========================================================================

makefileheader
include $SRCDIR/genmakefile
makefilefooter

exit 0
